#ifndef LEREVENTO_H_INCLUDED
#define LEREVENTO_H_INCLUDED

enum {NO_EVENT, CIMA, BAIXO, DIREITA, ESQUERDA, ENTER, ALARME_POT, ALARME_LDR}teclas;
int Lerevento (void);

#endif /* LEREVENTO_H_INCLUDED */
